log:
  level: info

plugins:
  - tag: mem_cache
    type: cache
    args:
      size: 40960
      lazy_cache_ttl: 259200
      lazy_cache_reply_ttl: 30

  - tag: forward_upstream
    type: fast_forward
    args:
      upstream:
        - addr: https://root.hagezi.org/dns-query
          trusted: true
          enable_pipeline: true
        - addr: https://wurzn.hagezi.org/dns-query
          trusted: true
          enable_pipeline: true
        - addr: https://juuri.hagezi.org/dns-query
          trusted: true
          enable_pipeline: true

  - tag: forward
    type: sequence
    args:
      exec:
        - mem_cache
        - forward_upstream
        - _return

servers:
  - exec: forward
    timeout: 5
    listeners:
      - protocol: http
        addr: ":PORT_PLACEHOLDER"
        url_path: "PATH_PLACEHOLDER"
        get_user_ip_from_header: "X-Forwarded-For"
